name: finkegabriel_deploy
on:
  push:
    branches:
      - main
env: 
  CI: false
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [15.13.0]
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Packages
        run: npm i
      - name: Deploy to GH Pages 
        run: | 
            git config --global user.email ${{secrets.EMAIL}}
            git config --global user.name ${{secrets.USERNAME}}
            git remote set-url origin https://${{secrets.PERSONAL_TOKEN}}@github.com/${{secrets.USERNAME}}/finkegabriel.git
            npm run add-domain
            npm run deploy
      - name: Updating Domain
        run: echo "Domain should auto update :)"